const DataAD = [
    {
        id: 1,
        MainTopic: "بيان النمط السليم للحياة الصحية",
        Subtopic: "التغذية السليمة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 2,
        MainTopic: "بيان النمط السليم للحياة الصحية",
        Subtopic: "النشاط البدنى وممارسة الرياضة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 3,
        MainTopic: "بيان النمط السليم للحياة الصحية",
        Subtopic: "مكافحة التدخين والإدمان",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 4,
        MainTopic: "بيان النمط السليم للحياة الصحية",
        Subtopic: "العمود الفقري وضعف الابصار",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 5,
        MainTopic: "بيان النمط السليم للحياة الصحية",
        Subtopic: "النظافة الشخصية ",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 6,
        MainTopic: "بيان النمط السليم للحياة الصحية",
        Subtopic: "صحة الفم والأسنان",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 7,
        MainTopic: "بيان النمط السليم للحياة الصحية",
        Subtopic: "تغذية ما قبل  وأثناء الحمل وبعد الولادة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 8,
        MainTopic: "بيان النمط السليم للحياة الصحية",
        Subtopic: "إدمان الإنترنت والهواتف الذكية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 9,
        MainTopic: "بيان النمط السليم للحياة الصحية",
        Subtopic: "سوء استخدام المضادت الحيوية والعقاقير",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 10,
        MainTopic: "بيان التوعية للوقاية والإكتشاف المبكر للأمراض غير المعدية",
        Subtopic: "أمراض القلب والأوعية الدموية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 11,
        MainTopic: "بيان التوعية للوقاية والإكتشاف المبكر للأمراض غير المعدية",
        Subtopic: "داء السكري",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 12,
        MainTopic: "بيان التوعية للوقاية والإكتشاف المبكر للأمراض غير المعدية",
        Subtopic: "ارتفاع ضغط الدم",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 13,
        MainTopic: "بيان التوعية للوقاية والإكتشاف المبكر للأمراض غير المعدية",
        Subtopic: "الأورام",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 14,
        MainTopic: "بيان التوعية للوقاية والإكتشاف المبكر للأمراض غير المعدية",
        Subtopic: "السمنة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 15,
        MainTopic: "بيان الوقاية من الامراض المعدية",
        Subtopic: "الأمراض الطفيلية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 16,
        MainTopic: "بيان الوقاية من الامراض المعدية",
        Subtopic: "الالتهاب الكبدي الفيروسي ",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 17,
        MainTopic: "بيان الوقاية من الامراض المعدية",
        Subtopic: "الانفلونزا الموسمية والمستجدة و الفيروس التنفسى المخلوى و كوفيد 19  - فيروس كورونا المستجد",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 18,
        MainTopic: "بيان الوقاية من الامراض المعدية",
        Subtopic: "الدرن",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 19,
        MainTopic: "بيان الوقاية من الامراض المعدية",
        Subtopic: "الأمراض المنقولة جنسيا والإيدز",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 20,
        MainTopic: "بيان الوقاية من الامراض المعدية",
        Subtopic: "الحصبة والحصبة الالماني",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 21,
        MainTopic: "بيان صحة الطفل",
        Subtopic: "نقص هرمون الغدة الدرقية وامراض التمثيل الغذائي  والفحص السمعي",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 22,
        MainTopic: "بيان صحة الطفل",
        Subtopic: "البطاقة الصحة و تطعيمات الاطفال",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 23,
        MainTopic: "بيان صحة الطفل",
        Subtopic: "رعاية المولود حديث الولادة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 24,
        MainTopic: "بيان صحة الطفل",
        Subtopic: "الرضاعة الطبيعية والتغذية التكميلية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 25,
        MainTopic: "بيان صحة الطفل",
        Subtopic: "سوء التغذية ( سمنة - تقزم - نقص الوزن - انيميا )",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 26,
        MainTopic: "بيان صحة الطفل",
        Subtopic: "أمراض الجهاز التنفسي",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 27,
        MainTopic: "بيان صحة الطفل",
        Subtopic: "الإسهال والجفاف",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 28,
        MainTopic: "بيان صحة الطفل",
        Subtopic: "التشجيع على الولادة الطبيعية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 29,
        MainTopic: "بيان الصحة العامة",
        Subtopic: "السلامة المنزلية و الإسعافات الأولية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 30,
        MainTopic: "بيان الصحة العامة",
        Subtopic: "الفحوص الطبية الروتينية والفحوص الدورية للسيدات",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 31,
        MainTopic: "بيان الصحة العامة",
        Subtopic: "الصحة النفسية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 32,
        MainTopic: "بيان الصحة العامة",
        Subtopic: "رعاية المسنين",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 33,
        MainTopic: "بيان الصحة العامة",
        Subtopic: "رعاية ذوي الاحتياجات الخاصة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 34,
        MainTopic: "بيان الصحة العامة",
        Subtopic: "أهمية التبرع بالدم / التبرع بالبلازما",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 35,
        MainTopic: "بيان الصحة العامة",
        Subtopic: "الأمراض الجلدية ",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 36,
        MainTopic: "بيان الصحة العامة",
        Subtopic: "مشروبات الطاقة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 37,
        MainTopic: "بيان الصحة العامة",
        Subtopic: "التوعية بالسعار (داء الكلب)",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 38,
        MainTopic: "صحة البيئة",
        Subtopic: "التغيرات المناخية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 39,
        MainTopic: "صحة البيئة",
        Subtopic: "الحد من استخدام البلاستيك الأحادي الإستخدام",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 40,
        MainTopic: "صحة البيئة",
        Subtopic: " البيئة الصحية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 41,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "دعم صحة المرأة المصرية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 42,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "دعم صحة الأم والجنين",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 43,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "اكتشاف وعلاج ضعف وفقدان السمع للأطفال حديثي الولادة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 44,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "متابعة وعلاج الأمراض المزمنة والكشف المبكر عن الاعتلال الكلوي",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 45,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "الكشف عن السمنة والأنيميا والتقزم لطلاب المدارس الإبتدائية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 46,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "الرعاية الصحية والنفسية المستمرة لكبار السن",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 47,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "الكشف عن فيروس سي بين طلاب المدارس الإعدادية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 48,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "مبادرة فحص المقبلين على الزواج",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 49,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "مبادرة الكشف المبكر و علاج الأورام السرطانية",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 50,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "مبادرة رئيس الجمهورية (الألف يوم الذهبية لتنمية الأسرة المصرية )",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 51,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "مبادرة كل ثانية حياة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 52,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "مبادرة صحتك سعادة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
    {
        id: 53,
        MainTopic: "مبادرات رئاسية وحملات توعية",
        Subtopic: "حملة 365 يوم سلامة",
        in: false,
        out: false,
        child: 0,
        men: 0,
        women: 0,
    },
];

// module.exports = DataAD;
